/**
 * Mock detection layer — DEMO ONLY.
 *
 * Every result produced here is generated by simple heuristics running in the
 * browser. It is NOT real threat intelligence and must always be surfaced in
 * the UI with a "Demo Analysis" label (see `demo: true` on ScanResult).
 *
 * Replace this module with real FastAPI calls (see services/api.ts).
 */

import type {
  Indicator,
  MessageAnalysis,
  ScanResult,
  Severity,
  TechnicalAnalysis,
  UrlAnalysis,
} from "@/types/scan";
import { riskLevelFromScore } from "@/types/scan";

export const DEMO_SCAM_URL = "https://paytm-secure-login-example.com";
export const DEMO_SAFE_URL = "https://example.com";
export const DEMO_SCAM_MESSAGE =
  "Your KYC will expire today. Click this link immediately to prevent your account from being blocked. http://kyc-update-verify.example.net";

const idle: TechnicalAnalysis = {
  url_engine: "not_applicable",
  ocr_engine: "not_applicable",
  qr_engine: "not_applicable",
  nlp_engine: "not_applicable",
  threat_intel: "not_applicable",
  risk_engine: "complete",
};

function newId() {
  return `scan_${Math.random().toString(36).slice(2, 8)}${Date.now().toString(36).slice(-4)}`;
}

function severityWeight(s: Severity) {
  return { info: 2, low: 8, medium: 16, high: 24, critical: 32 }[s];
}

function scoreFrom(indicators: Indicator[], base = 6) {
  const raw = indicators.reduce((sum, i) => sum + severityWeight(i.severity), base);
  return Math.max(3, Math.min(98, Math.round(raw)));
}

function confidenceFrom(indicators: Indicator[]) {
  return Math.min(0.95, 0.62 + indicators.length * 0.06);
}

const BRANDS = [
  "paytm",
  "phonepe",
  "gpay",
  "googlepay",
  "sbi",
  "hdfc",
  "icici",
  "axis",
  "airtel",
  "jio",
  "amazon",
  "flipkart",
  "irctc",
  "epfo",
  "uidai",
  "aadhaar",
];

const SUSPICIOUS_KEYWORDS = [
  "secure",
  "login",
  "verify",
  "update",
  "kyc",
  "account",
  "wallet",
  "refund",
  "offer",
  "reward",
  "bonus",
  "otp",
];

/* ------------------------------ URL analysis ------------------------------ */

export function analyzeUrlMock(rawUrl: string): ScanResult {
  const url = new URL(rawUrl);
  const host = url.hostname.toLowerCase();
  const labels = host.split(".");
  const indicators: Indicator[] = [];

  const brandHit = BRANDS.find((b) => host.includes(b));
  const isBrandDomain = brandHit ? host === `${brandHit}.com` || host.endsWith(`.${brandHit}.com`) : false;

  if (brandHit && !isBrandDomain) {
    indicators.push({
      severity: "high",
      title: "Possible brand impersonation",
      description: `The hostname contains the brand term "${brandHit}" but is not an official ${brandHit} domain.`,
      details: `Hostname: ${host}. A legitimate brand page is normally served from the brand's own registered domain, not from a look-alike domain that merely contains the brand name.`,
    });
  }

  const keywordHits = SUSPICIOUS_KEYWORDS.filter((k) => host.includes(k));
  if (keywordHits.length >= 2) {
    indicators.push({
      severity: "high",
      title: "Suspicious domain structure",
      description: `Domain combines multiple trust/urgency keywords: ${keywordHits.join(", ")}.`,
      details:
        "Phishing kits often stack words like secure, login, verify and kyc into a hostname so the URL looks official at a glance on a small screen.",
    });
  } else if (keywordHits.length === 1) {
    indicators.push({
      severity: "medium",
      title: "Trust keyword in domain",
      description: `Domain contains the keyword "${keywordHits[0]}".`,
    });
  }

  if (url.protocol !== "https:") {
    indicators.push({
      severity: "high",
      title: "Insecure connection (no HTTPS)",
      description: "Data sent to this site is not encrypted in transit.",
    });
  }

  if (labels.length > 3) {
    indicators.push({
      severity: "medium",
      title: "Deep subdomain nesting",
      description: `${labels.length - 2} subdomain level(s) detected, a common way to hide the real domain.`,
    });
  }

  const params = Array.from(url.searchParams.keys());
  const suspiciousParams = params.filter((p) =>
    ["redirect", "next", "url", "token", "otp", "pin", "return"].some((s) => p.toLowerCase().includes(s)),
  );
  if (suspiciousParams.length) {
    indicators.push({
      severity: "medium",
      title: "Suspicious redirect parameters",
      description: `Parameters that can forward you elsewhere: ${suspiciousParams.join(", ")}.`,
    });
  }

  if (rawUrl.length > 75) {
    indicators.push({
      severity: "low",
      title: "Unusually long URL",
      description: `${rawUrl.length} characters — long URLs help hide the real destination.`,
    });
  }

  if (/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) {
    indicators.push({
      severity: "critical",
      title: "Raw IP address instead of a domain",
      description: "Legitimate consumer services almost never ask you to open a bare IP address.",
    });
  }

  if (/(login|signin|verify|kyc|payment)/.test(url.pathname.toLowerCase())) {
    indicators.push({
      severity: "medium",
      title: "Login/payment-related path",
      description: `Path "${url.pathname}" suggests a credential or payment page.`,
    });
  }

  if (!indicators.length) {
    indicators.push({
      severity: "info",
      title: "No structural red flags found",
      description:
        "Demo heuristics did not find impersonation, keyword stuffing or redirect tricks in this URL.",
    });
  }

  const score = scoreFrom(indicators, indicators[0].severity === "info" ? 5 : 10);
  const url_analysis: UrlAnalysis = {
    domain: host,
    protocol: url.protocol.replace(":", "").toUpperCase(),
    url_length: rawUrl.length,
    subdomains: Math.max(0, labels.length - 2),
    suspicious_params: suspiciousParams.length,
    https: url.protocol === "https:",
    domain_reputation: null,
    typosquatting: brandHit && !isBrandDomain ? "Possible" : null,
  };

  return {
    scan_id: newId(),
    input_type: "url",
    target: rawUrl,
    created_at: new Date().toISOString(),
    risk_score: score,
    risk_level: riskLevelFromScore(score),
    confidence: confidenceFrom(indicators),
    summary:
      score > 60
        ? "This URL shows several structural indicators commonly seen in phishing pages."
        : score > 30
          ? "This URL shows a few weak indicators. Treat it with caution."
          : "No strong structural scam indicators were found in this URL.",
    demo: true,
    indicators,
    recommendations:
      score > 60
        ? [
            "Do not enter your login credentials on this site.",
            "Do not enter card details, OTP or UPI PIN.",
            "Open the brand's official app or type the official domain manually.",
            "Report the link to your bank or to cybercrime.gov.in if you were targeted.",
          ]
        : [
            "Still verify the domain spelling character by character.",
            "Avoid entering sensitive details unless you started the interaction.",
            "Prefer official apps over links received in messages.",
          ],
    technical_analysis: {
      ...idle,
      url_engine: "complete",
      nlp_engine: "complete",
      threat_intel: "unavailable",
      risk_engine: "complete",
    },
    url_analysis,
  };
}

/* ---------------------------- Message analysis ---------------------------- */

const URGENCY_WORDS = [
  "immediately",
  "urgent",
  "today",
  "within 24 hours",
  "last chance",
  "expire",
  "expiring",
  "blocked",
  "suspend",
  "deactivat",
];
const CREDENTIAL_WORDS = ["otp", "pin", "cvv", "password", "atm pin", "upi pin", "netbanking"];
const FINANCIAL_WORDS = ["₹", "rs.", "rupees", "payment", "pay ", "transfer", "refund", "cashback", "upi", "bank"];
const REWARD_WORDS = ["won", "winner", "lottery", "prize", "congratulations", "reward", "bonus", "gift"];

export function analyzeMessageMock(message: string): ScanResult {
  const text = message.toLowerCase();
  const indicators: Indicator[] = [];

  const urgencyHits = URGENCY_WORDS.filter((w) => text.includes(w));
  if (urgencyHits.length) {
    indicators.push({
      severity: urgencyHits.length > 1 ? "high" : "medium",
      title: "Urgency language detected",
      description: `Pressure phrases found: ${urgencyHits.join(", ")}.`,
      details: "Scammers create time pressure so you act before verifying through an official channel.",
    });
  }

  if (text.includes("kyc")) {
    indicators.push({
      severity: "high",
      title: "KYC-related language",
      description: "Fake KYC-expiry notices are one of the most common scam formats in India.",
      details: "Banks do not complete KYC through a link in an SMS or WhatsApp message.",
    });
  }

  const credHits = CREDENTIAL_WORDS.filter((w) => text.includes(w));
  if (credHits.length) {
    indicators.push({
      severity: "critical",
      title: "Sensitive information requested",
      description: `Message references: ${credHits.join(", ")}.`,
      details: "No legitimate bank, wallet or government body will ever ask for these.",
    });
  }

  const linkMatch = message.match(/https?:\/\/[^\s]+/i);
  if (linkMatch) {
    indicators.push({
      severity: "high",
      title: "Suspicious link in message",
      description: `The message contains a link: ${linkMatch[0]}`,
      details: "Links inside unsolicited messages are the primary delivery method for phishing pages.",
    });
  }

  const rewardHits = REWARD_WORDS.filter((w) => text.includes(w));
  if (rewardHits.length) {
    indicators.push({
      severity: "high",
      title: "Unexpected reward or prize offer",
      description: `Reward wording found: ${rewardHits.join(", ")}.`,
    });
  }

  const financialHits = FINANCIAL_WORDS.filter((w) => text.includes(w));
  if (financialHits.length) {
    indicators.push({
      severity: "medium",
      title: "Payment or money-related request",
      description: `Financial wording found: ${financialHits.join(", ")}.`,
    });
  }

  const brandHit = BRANDS.find((b) => text.includes(b));
  if (brandHit) {
    indicators.push({
      severity: "medium",
      title: "Brand name referenced",
      description: `The message mentions "${brandHit}". This alone does not make it a scam, but combined with urgency or links it is a common impersonation pattern.`,
    });
  }

  if (!indicators.length) {
    indicators.push({
      severity: "info",
      title: "No common scam patterns detected",
      description: "Demo NLP heuristics found no urgency, credential requests, links or reward bait.",
    });
  }

  const score = scoreFrom(indicators, 5);
  const message_analysis: MessageAnalysis = {
    urgency: urgencyHits.length > 1 ? "HIGH" : urgencyHits.length ? "MEDIUM" : "NONE",
    financial_request: financialHits.length ? "DETECTED" : "NOT_DETECTED",
    credential_request: credHits.length ? "DETECTED" : "NOT_DETECTED",
    brand_impersonation: brandHit ? "POSSIBLE" : "NOT_DETECTED",
    suspicious_link: linkMatch ? "DETECTED" : "NOT_DETECTED",
  };

  return {
    scan_id: newId(),
    input_type: "message",
    target: message.slice(0, 90),
    created_at: new Date().toISOString(),
    risk_score: score,
    risk_level: riskLevelFromScore(score),
    confidence: confidenceFrom(indicators),
    summary:
      score > 60
        ? "This message uses several manipulation patterns typical of Indian phishing campaigns."
        : score > 30
          ? "This message contains a few weak scam signals."
          : "No strong scam patterns were detected in this message.",
    demo: true,
    indicators,
    recommendations:
      score > 40
        ? [
            "Do not enter your OTP anywhere because of this message.",
            "Do not share your UPI PIN, CVV or password.",
            "Do not tap links inside the message.",
            "Do not install any app it asks you to download.",
            "Call the official customer care number printed on your card or the official app.",
          ]
        : [
            "Verify the sender before replying.",
            "Never act on payment instructions received only over messaging.",
          ],
    technical_analysis: {
      ...idle,
      nlp_engine: "complete",
      url_engine: linkMatch ? "complete" : "not_applicable",
      threat_intel: "unavailable",
      risk_engine: "complete",
    },
    message_analysis,
  };
}

/* --------------------------- Screenshot analysis -------------------------- */

export function analyzeScreenshotMock(fileName: string): ScanResult {
  const indicators: Indicator[] = [
    {
      severity: "critical",
      title: "Credential request detected in image",
      description: 'Extracted text includes an OTP entry prompt.',
      details: "OCR line: “Enter your OTP”. Genuine banking apps never ask for an OTP on a web overlay.",
    },
    {
      severity: "high",
      title: "Bank impersonation layout",
      description: "The extracted copy mimics a bank verification screen.",
    },
    {
      severity: "high",
      title: "Account threat / urgency language",
      description: 'Extracted text includes “Your account will be blocked”.',
    },
  ];
  const score = scoreFrom(indicators, 12);

  return {
    scan_id: newId(),
    input_type: "screenshot",
    target: fileName,
    created_at: new Date().toISOString(),
    risk_score: score,
    risk_level: riskLevelFromScore(score),
    confidence: 0.88,
    summary:
      "Demo OCR analysis found credential-request and account-threat wording typical of a phishing screen.",
    demo: true,
    indicators,
    recommendations: [
      "Do not enter your OTP on this screen.",
      "Do not enter card number, expiry or CVV.",
      "Close the page and open your bank's official app instead.",
      "If you already shared details, call your bank and block the card immediately.",
    ],
    technical_analysis: {
      ...idle,
      ocr_engine: "complete",
      nlp_engine: "complete",
      threat_intel: "unavailable",
      risk_engine: "complete",
    },
    ocr_analysis: {
      extracted_text: [
        "Enter your OTP",
        "Verify your bank account",
        "Your account will be blocked within 24 hours",
        "Continue to secure verification",
      ],
      detected_patterns: [
        "Urgency language",
        "Credential request",
        "Bank impersonation",
        "Account threat",
      ],
    },
  };
}

/* ------------------------------- QR analysis ------------------------------ */

export function analyzeQrMock(fileName: string): ScanResult {
  const indicators: Indicator[] = [
    {
      severity: "high",
      title: "Collect-money request disguised as payout",
      description:
        "The decoded UPI intent requests money FROM you. A QR code can never send money to you.",
      details:
        "Demo decode: upi://pay?pa=example@upi&pn=Example%20Merchant&am=500.00&cu=INR. Scanning a QR always initiates a debit from your account.",
    },
    {
      severity: "medium",
      title: "Unverified payee name",
      description: "The payee handle does not match a verified merchant record.",
    },
    {
      severity: "medium",
      title: "Pre-filled amount",
      description: "A fixed ₹500 amount is embedded in the code, a common refund/cashback scam pattern.",
    },
  ];
  const score = scoreFrom(indicators, 10);

  return {
    scan_id: newId(),
    input_type: "qr",
    target: fileName,
    created_at: new Date().toISOString(),
    risk_score: score,
    risk_level: riskLevelFromScore(score),
    confidence: 0.86,
    summary: "Demo QR decode resolves to a UPI collect request. Verify the recipient before paying.",
    demo: true,
    indicators,
    recommendations: [
      "Never scan a QR code to *receive* money — QR scans only send money.",
      "Do not enter your UPI PIN for an incoming payment.",
      "Confirm the payee name in your UPI app before approving anything.",
      "Cancel the request if you did not initiate the purchase.",
    ],
    technical_analysis: {
      ...idle,
      qr_engine: "complete",
      url_engine: "not_applicable",
      nlp_engine: "complete",
      threat_intel: "unavailable",
      risk_engine: "complete",
    },
    qr_analysis: {
      qr_type: "UPI",
      decoded_data: "upi://pay?pa=example@upi&pn=Example%20Merchant&am=500.00&cu=INR",
      payee: "Example Merchant",
      upi_id: "example@upi",
      amount: 500,
      currency: "INR",
    },
  };
}

/* ------------------------------ Seeded demo ------------------------------ */

export function seedHistory(): ScanResult[] {
  const samples: ScanResult[] = [
    analyzeUrlMock(DEMO_SCAM_URL),
    analyzeMessageMock(DEMO_SCAM_MESSAGE),
    analyzeUrlMock(DEMO_SAFE_URL),
    analyzeQrMock("upi-refund-qr.png"),
    analyzeMessageMock("Congratulations! You won ₹50,000 in the lucky draw. Claim now, offer expires today."),
    analyzeScreenshotMock("bank-verification.png"),
  ];
  const now = Date.now();
  return samples.map((s, i) => ({
    ...s,
    created_at: new Date(now - (i + 1) * 7 * 3600_000).toISOString(),
  }));
}
