import { Link } from "@tanstack/react-router";
import { Logo } from "@/components/brand/Logo";
import { ShieldAlert } from "lucide-react";

export function Footer() {
  return (
    <footer className="border-t border-border bg-surface/40">
      <div className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-4">
        <div className="md:col-span-2">
          <div className="flex items-center gap-2.5">
            <Logo className="h-8 w-8" />
            <span className="font-display text-lg font-bold">
              Scam<span className="text-primary">Shield</span>
            </span>
          </div>
          <p className="mt-3 max-w-sm text-sm text-muted-foreground">
            Scan Before You Trust. Multi-modal scam detection for websites, screenshots, QR codes and
            messages — built for Indian users.
          </p>
          <p className="mt-4 flex items-start gap-2 rounded-lg border border-medium/30 bg-medium/10 p-3 text-xs text-muted-foreground">
            <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-medium" aria-hidden />
            <span>
              ScamShield never asks for your OTP, PIN, password or card details. Analysis results are
              advisory and, in this build, generated by a demo engine.
            </span>
          </p>
        </div>

        <div>
          <h3 className="text-sm font-semibold">Product</h3>
          <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
            <li>
              <Link to="/scan" className="hover:text-primary">
                Scanner
              </Link>
            </li>
            <li>
              <Link to="/dashboard" className="hover:text-primary">
                Dashboard
              </Link>
            </li>
            <li>
              <Link to="/history" className="hover:text-primary">
                Scan history
              </Link>
            </li>
          </ul>
        </div>

        <div>
          <h3 className="text-sm font-semibold">Resources</h3>
          <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
            <li>
              <Link to="/learn" className="hover:text-primary">
                Learn to spot a scam
              </Link>
            </li>
            <li>
              <Link to="/about" className="hover:text-primary">
                About &amp; architecture
              </Link>
            </li>
            <li>
              <a
                href="https://cybercrime.gov.in"
                target="_blank"
                rel="noreferrer noopener"
                className="hover:text-primary"
              >
                Report cybercrime (India)
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div className="border-t border-border py-5 text-center text-xs text-muted-foreground">
        ScamShield — Scan Before You Trust. Demo build for education and research.
      </div>
    </footer>
  );
}
