import { FlaskConical } from "lucide-react";
import { cn } from "@/lib/utils";

/** Marks any output that came from the local demo engine rather than a real backend. */
export function DemoBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border border-medium/40 bg-medium/10 px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-medium",
        className,
      )}
      title="Generated by the built-in demo engine, not real-time threat intelligence"
    >
      <FlaskConical className="h-3.5 w-3.5" aria-hidden />
      Demo Analysis
    </span>
  );
}
